### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by baudouxbenjamin** [massoudss/waveformSeekBar#11]
Hi,

I got the following error when using your librarie:

> java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/appli.speaky.com.debug-HBTfQoCC8f4atW-yZnZPGQ==/base.apk"],nativeLibraryDirectories=[/data/app/appli.speaky.com.debug-HBTfQoCC8f4atW-yZnZPGQ==/lib/x86, /data/app/appli.speaky.com.debug-HBTfQoCC8f4atW-yZnZPGQ==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libnative-lib.so"

I'm using the `2.0.0`version.

**Comment by lincollincol** [comment]
Hello @baudouxbenjamin ! I want to see a piece of your code. Can you share it?

**Comment by baudouxbenjamin** [comment]
Hi @lincollincol ! Yes I'm testing on an android emulator which is used when I debug as well as during my tests on the CI. Will you support it in a future version of Amplituda? Also, is the `android:extractNativeLibs="false"` mandatory or not?

**Comment by lincollincol** [comment]
@baudouxbenjamin 
1. Amplituda will support x86 in the future. I'm currently not working on this project, but continue soon.
2. Sure, I recommend you to use `android:extractNativeLibs="false"`, because it reduces your app size. Android studio hint says that it's not mandatory in new android versions, but I prefer to use this attribute. You can also compare app size with and without this attribute.
